# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 87b5aeb682d2dcdb4910e8d838827be2971ed1e3ec13834bf9316d48b6246ecdc7dca9b7d04fa9ed84f11ade420a59f612d5b2feeab131884e6c096fc3c99caf
  db_user: development
  db_database: pana-nonverbal-validation2_development
  db_password:
  db_host: localhost
  export_password: test

test:
  secret_key_base: 3c4b689013bb1ecee4fec91d43978a13b92063067b040a895b27a57e92cc8bd9c68fbec860fd9aa2dbc6c9e49fc547e0cd482d61ce0a348b7a9b347ce4c5b764
  db_user: development
  db_database: pana-nonverbal-validation2_test
  db_password:
  db_host: localhost
  export_password: test
